insert into user(first_name, last_name, status) values ('Virginie', 'Bastiere', 'STUDENT')
insert into user(first_name, last_name, status) values ('Dominique', 'Merlet', 'STUDENT')
insert into user(first_name, last_name, status) values ('Vincent', 'Lavau', 'STUDENT')
insert into user(first_name, last_name, status) values ('Christophe', 'Girault', 'STUDENT')
insert into user(first_name, last_name, status) values ('Chris', 'Woodrow', 'TRAINER')
